name: Build Executable and Installer on Release
on:
  release:
    types: [created]
  workflow_dispatch:  # Keep manual trigger for testing
    inputs:
      debug_mode:
        description: 'Enable debug mode (shows more detailed output)'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows Executable and Installer
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get release version
        id: get_version
        run: |
          if ("${{ github.event_name }}" -eq "release") {
            $version = "${{ github.event.release.tag_name }}" -replace '^v', ''
            echo "version=$version" >> $env:GITHUB_OUTPUT
            echo "release_name=${{ github.event.release.name }}" >> $env:GITHUB_OUTPUT
            echo "is_release=true" >> $env:GITHUB_OUTPUT
          } else {
            $version = "dev-$(Get-Date -Format 'yyyyMMdd-HHmm')"
            echo "version=$version" >> $env:GITHUB_OUTPUT
            echo "release_name=Development Build" >> $env:GITHUB_OUTPUT
            echo "is_release=false" >> $env:GITHUB_OUTPUT
          }
          echo "Using version: $version"

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync --locked --all-extras --dev
      
      - name: Install scilslab wheels
        run: uv add wheels\scilslab-8.1.122-cp313-cp313-win_amd64.whl

      - name: Show Python and package info (debug)
        if: ${{ inputs.debug_mode == true || inputs.debug_mode == '' }}
        run: |
          echo "=== Python Environment Info ==="
          uv run python --version
          echo "=== UV Info ==="
          uv --version
          echo "=== Installed packages ==="
          uv run pip list
          echo "=== Current directory ==="
          pwd
          dir

      - name: Update Inno Setup script with version
        run: |
          $version = "${{ steps.get_version.outputs.version }}"
          $content = Get-Content "setup.iss" -Raw
          $content = $content -replace 'AppVersion=.*', "AppVersion=$version"
          $content = $content -replace 'OutputBaseFilename=.*', "OutputBaseFilename=PeakFinderPro-Setup-v$version"
          Set-Content "setup.iss" $content
          echo "Updated setup.iss with version: $version"
          echo "=== First 15 lines of setup.iss ==="
          Get-Content "setup.iss" | Select-Object -First 15

      - name: Build executable with PyInstaller
        run: |
          echo "=== Starting PyInstaller build ==="
          uv run pyinstaller feature_extractor_gui.py --clean --noconfirm
          echo "=== PyInstaller build completed ==="
        
      - name: List dist contents (debug)
        run: |
          echo "=== Contents of dist directory ==="
          if (Test-Path "dist") {
            Get-ChildItem -Recurse "dist" | ForEach-Object { 
              $relativePath = $_.FullName.Replace((Get-Location).Path + "\", "")
              if ($_.PSIsContainer) {
                echo "DIR:  $relativePath"
              } else {
                $size = if ($_.Length -gt 1MB) { "$([math]::Round($_.Length / 1MB, 2)) MB" } else { "$($_.Length) bytes" }
                echo "FILE: $relativePath ($size)"
              }
            }
          } else {
            echo "❌ dist directory not found"
          }
          echo "=== Contents of build directory ==="
          if (Test-Path "build") {
            Get-ChildItem -Recurse "build" | Select-Object -First 20 | ForEach-Object {
              $relativePath = $_.FullName.Replace((Get-Location).Path + "\", "")
              echo "BUILD: $relativePath"
            }
          } else {
            echo "build directory not found"
          }
          echo "=== Contents of current directory ==="
          Get-ChildItem | ForEach-Object { echo $_.Name }
          
      - name: Test executable
        run: |
          echo "=== Testing if executable was created ==="
          if (Test-Path "dist\PeakFinderPro\PeakFinderPro.exe") {
            echo "✅ Executable created successfully"
            $fileInfo = Get-Item 'dist\PeakFinderPro\PeakFinderPro.exe'
            echo "File size: $($fileInfo.Length) bytes ($([math]::Round($fileInfo.Length / 1MB, 2)) MB)"
            echo "Created: $($fileInfo.CreationTime)"
            echo "=== Contents of PeakFinderPro directory ==="
            dir "dist\PeakFinderPro" | Format-Table Name, Length, LastWriteTime
          } else {
            echo "❌ Executable not found"
            echo "=== Looking for any .exe files ==="
            Get-ChildItem -Recurse -Filter "*.exe" | ForEach-Object { echo $_.FullName }
            exit 1
          }

      - name: Create portable ZIP
        run: |
          echo "=== Creating portable ZIP ==="
          if (Test-Path "dist\PeakFinderPro") {
            $version = "${{ steps.get_version.outputs.version }}"
            $zipName = "PeakFinderPro-Portable-v$version.zip"
            Compress-Archive -Path "dist\PeakFinderPro\*" -DestinationPath $zipName
            echo "✅ ZIP created successfully: $zipName"
            $zipInfo = Get-Item $zipName
            echo "ZIP size: $($zipInfo.Length) bytes ($([math]::Round($zipInfo.Length / 1MB, 2)) MB)"
            echo "zip_name=$zipName" >> $env:GITHUB_OUTPUT
          } else {
            echo "❌ Source directory not found for ZIP creation"
            exit 1
          }

      - name: Compile Inno Setup Installer
        run: |
          echo "=== Starting Inno Setup compilation ==="
          echo "Checking if setup.iss exists..."
          if (Test-Path "setup.iss") {
            echo "✅ setup.iss found"
            Get-Content "setup.iss" | Select-Object -First 10
          } else {
            echo "❌ setup.iss not found"
            exit 1
          }
        continue-on-error: true

      - name: Run Inno Setup Action
        id: inno_setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: setup.iss
          options: /O+ /Qp

      - name: Find installer file
        id: find_installer
        run: |
          echo "=== Finding installer file ==="
          $installerFile = $null
          if (Test-Path "installer") {
            $installerFile = Get-ChildItem "installer" -Filter "*.exe" | Select-Object -First 1
          }
          if (-not $installerFile) {
            $installerFile = Get-ChildItem -Filter "PeakFinderPro-Setup*.exe" | Select-Object -First 1
          }
          if ($installerFile) {
            echo "Found installer: $($installerFile.FullName)"
            echo "installer_path=$($installerFile.FullName)" >> $env:GITHUB_OUTPUT
            echo "installer_name=$($installerFile.Name)" >> $env:GITHUB_OUTPUT
          } else {
            echo "❌ No installer file found"
            exit 1
          }

      - name: List installer output (debug)
        run: |
          echo "=== Checking for installer output ==="
          echo "Contents of installer directory:"
          if (Test-Path "installer") {
            Get-ChildItem "installer" | ForEach-Object { echo "  $($_.Name) - $($_.Length) bytes" }
            echo "=== Installer files found ==="
            Get-ChildItem "installer" -Filter "*.exe" | ForEach-Object { 
              echo "Installer: $($_.Name) - Size: $($_.Length) bytes"
            }
          } else {
            echo "Installer directory not found, checking current directory:"
            Get-ChildItem -Filter "*.exe" | ForEach-Object { echo "  $($_.Name)" }
            echo "=== All directories ==="
            Get-ChildItem -Directory | ForEach-Object { echo "Directory: $($_.Name)" }
          }

      - name: Upload Portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: PeakFinderPro-Portable-${{ steps.get_version.outputs.version }}
          path: PeakFinderPro-Portable-v${{ steps.get_version.outputs.version }}.zip
          retention-days: 90

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: PeakFinderPro-Installer-${{ steps.get_version.outputs.version }}
          path: ${{ steps.find_installer.outputs.installer_path }}
          retention-days: 90

      - name: Upload Release Assets
        if: steps.get_version.outputs.is_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PeakFinderPro-Portable-v${{ steps.get_version.outputs.version }}.zip
            ${{ steps.find_installer.outputs.installer_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}